name: slideshow
description: System modeling playground
dockerbuild:
- name: slideshow
  dockerfile: dockerfile
  context: .
  build_arg:
  - key: IMAGE
    value: ubuntu:20.04
version:
  major: 0
  minor: 0
  patch: 37
  label: ''
gpus: all
registry: 192.168.0.163:9090
image_names:
- name: slideshow
  image_name: 192.168.0.163:9089/slideshow:0.0.37
